django_app/content/urls.py
from django.urls import path
from . import views

app_name = 'content'
urlpatterns = [
    path('', views.main, name='main'),
    path('top_tags/', views.top_ten_tag, name='tags'),
    path('add_tags/', views.add_tag, name='add_tags'),
    path('add_quote/', views.add_quote, name='add_quote')
]

django_app/django_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('content.urls')),
    path('users/', include('users.urls'))
]

django_app/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout')
]

django_app/content/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=30, null=False, unique=True)

    def __str__(self):
        return self.name
    
class Tag(models.Model):
    tags = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.tags

class Quote(models.Model):
    quote = models.TextField(null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.quote

django_app/users/models.py
from django.db import models

# Create your models here.

django_app/content/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import Tag, Quote, Author

class AuthorForm(ModelForm):
    name = CharField(min_length=3, max_length=30, required=True, widget=TextInput)
    
    class Meta:
        model = Author
        fields = ['name']

class TagForm(ModelForm):

    tags = CharField(min_length=3, max_length=100, required=True, widget=TextInput)

    class Meta:
        model = Tag
        fields = ['tags']

class QuoteForm(ModelForm):

    author = AuthorForm()
    quote = CharField(min_length=3, max_length=180, required=True, widget=TextInput)

    class Meta:
        model = Quote
        fields = ['author', 'quote']
        exclude = ['tags']

django_app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

class RegisterForm(UserCreationForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput())

    password1 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())
    password2 = forms.CharField(max_length=50,
                                required=True,
                                widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

django_app/content/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .migrate_mongo_to_postrgres import feed_db
from .models import Tag, Author, Quote
from .forms import TagForm, QuoteForm

# Create your views here.
def main(request):
    print(feed_db())
    quotes = Quote.objects.all()
    return render(request, 'content/base.html', {'quotes': quotes})

def top_ten_tag(request):
    data = Tag.objects.all()
    unique_tag = []

    for tag in data:
        if tag in unique_tag:
            continue
        else:
            unique_tag.append(tag)
    
    return render(request, 'content/top_tags.html', {'tags': unique_tag[:10]})

def add_tag(request):
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            data = form.data.get('tags')
            split_data = data.rstrip().split(' ')
            for el in split_data:
                tags_from_form = Tag(tags=el).save()
            return redirect(to='content:main')
        else:
            return render(request, 'content/add_tags.html', {'form': form})
    
    return render(request, 'content/add_tags.html', {'form': TagForm()})

def add_quote(request):
    tags = Tag.objects.all()

    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            new_quote = form.save()

            choice_tags = Tag.objects.filter(tags__in=request.POST.getlist('tags'))
            for tag in choice_tags.iterator():
                new_quote.tags.add(tag)
            
            return redirect(to='content:main')
        else:
            return render(request, 'content/add_quote.html', {'tags': tags, 'form': form})
    return render(request, 'content/add_quote.html', {'tags': tags, 'form': QuoteForm()})

django_app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import RegisterForm, LoginForm


def loginuser(request):
    if request.user.is_authenticated:
        return redirect(to='content:main')

    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is None:
            messages.error(request, 'Username or password didn\'t match')
            return redirect(to='users:login')

        login(request, user)
        return redirect(to='content:main')

    return render(request, 'users/login.html', context={"form": LoginForm()})

@login_required
def logoutuser(request):
    logout(request)
    return redirect(to='content:main')

def signupuser(request):
    if request.user.is_authenticated:
        return redirect(to='content:main')

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(to='content:main')
        else:
            return render(request, 'users/signup.html', context={"form": form})

    return render(request, 'users/signup.html', context={"form": RegisterForm()})

django_app/content/templates/content/add_quote.html
{% extends "content/base.html" %}

{% block content %}

<form method="POST" action="{% url 'content:add_quote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author name:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div style="padding: 10px">
        <label> Quote:
            {{ form.quote  }}
        </label>
        <span>{{ form.errors.quote }}</span>
    </div>
    <div style="padding: 10px">
        <label> Select tags:
            <select name="tags" multiple="multiple" required>
                {% for tag in tags %}
                <option value="{{tag}}">{{tag}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

django_app/content/templates/content/add_tags.html
{% extends "content/base.html" %}

{% block content %}

<form method="POST" action="{% url 'content:add_tags' %}">
    {% csrf_token  %}
    <div style="padding: 10px;">
        <label>
            Add tags: 
            {{form.tags}}
        </label>
        <span>{{ form.errors.tags }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

django_app/content/templates/content/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes to Scrape</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'content/style.css' %}">
</head>
<body>
    <main class="container">
        <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
            <div class="row header-box">
                <div class="col-md-8">
                    <h1>
                        <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                    </h1>
                </div>
                <div class="col-md-4">
                    {% if user.is_authenticated %}
                    <ul>
                        <li><a href="{% url 'content:add_quote' %}" role="button">Add quote</a></li>
                        <li><a href="{% url 'content:add_tags' %}" role="button">Add Tag</a></li>
                    </ul>
                    <p>
                        <li>Welcome <b>{{ user.username }}!</b></li>
                        <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
                    </p>
                    {% else %}
                    <p>
                        <a href="users/login"><h3>Login</h3></a>
                    </p>
                    <p>
                        <a href="users/signup"><h3>Sign Up</h3></a>
                    </p>
                    {% endif %}
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-8">
                {% for quote in quotes %}
                <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
                    <span class="text" itemprop="text">{{ quote.quote }}</span>
                    <span>by <small class="author" itemprop="author">{{ quote.author }}</small>
                    </span>
                    <div class="tags">
                        Tags:
                        <meta class="keywords" itemprop="keywords" content="{{ quote.tags.all | join:', ' }}">
                        {% for tag in quote.tags.all %}
                        {{ tag }}
                        {% endfor %}
                    </div>
                </div>
                {% endfor %}
    
                <nav>
                    <ul class="pager">
                        {% if quotes.has_previous %}
                        <li class="previous">
                            <a href="{{ quotes.previous_page_number }}">← Previous</a>
                        </li>
                        {% endif %}
                        {% if quotes.has_next %}
                        <li class="next">
                            <a href="{{ quotes.next_page_number }}">Next →</a>
                        </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
            <div class="col-md-4 tags-box">
                <a href="/top_tags">
                    <h2>Top Ten tags</h2>
                </a>
                {% block content %} {% endblock %}
            </div>
        </div>
    </main>
</body>
</html>

django_app/content/templates/content/top_tags.html
{% extends "content/base.html" %}

{% block content %}

        {% for tag in tags %}
        <ul>
            <li>
                <span class="tag-item">
                    <a class="tag" style="font-size: 16px" href="#">{{ tag }} </a>
                </span>
            </li>
        </ul>
        {% endfor %}

{% endblock %}

django_app/users/templates/users/login.html
{% extends "content/base.html" %}

{% block content %}

{% if messages %}
<div>
    {% for message in messages %}
    <div {% if message.tags %} class="alert-{{ message.tags }}" {% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
    </div>

    <div>
        <label>Password:
            {{ form.password }}
        </label>
    </div>

    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}

django_app/users/templates/users/signup.html
{% extends "content/base.html" %}

{% block content %}

<form method="post" action="{% url 'users:signup' %}">
    {% csrf_token %}
    <div>
        <label> Username:
            {{ form.username }}
        </label>
        <span>{{ form.errors.username }}</span>
    </div>
    <br>
    <div>
        <label> Password:
            {{ form.password1 }}
        </label>
        <span>{{ form.errors.password1 }}</span>
    </div>
    <div>
        <label> Password confirmation:
            {{ form.password2 }}
        </label>
        <span>{{ form.errors.password2 }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>

{% endblock %}